version: '3.8'

volumes:
  static_volume:
  postgres_db:

services:
  db:
    image: postgres:12.0-alpine
    restart: always
    container_name: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    
  web:
    build: .
    container_name: web
    restart: always
    volumes:
      - static_volume:/code/static/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    container_name: webserver
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/static/
    ports:
      - "80:80"
    depends_on:
      - web