# Generated by Django 3.1.7 on 2021-03-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('questions_count', models.IntegerField(verbose_name='Количество вопросов')),
                ('score', models.IntegerField(verbose_name='Оценка теста')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
